In [1]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)     # X = (hours sleeping, hours studying)
y = np.array(([92], [86], [89]), dtype=float)           # y = score on test

# scale units
X = X/np.amax(X, axis=0)        # maximum of X array
y = y/100                       # max test score is 100

In [10]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputSize=2
        self.hiddenSize=3
        self.outputSize=1
        
        self.W1=np.random.randn(self.inputSize,self.hiddenSize)
        self.W2=np.random.randn(self.hiddenSize,self.outputSize)
        
    def forward(self,X):
        self.z=np.dot(X,self.W1)
        self.z2=self.sigmoid(self.z)
        self.z3=np.dot(self.z2,self.W2)
        o=self.sigmoid(self.z3)
        return o
    
    def backward(self, X,y,o):
        self.o_error=y-o
        self.o_delta=self.o_error*self.sigmoidPrime(o)
        self.z2_error=self.o_delta.dot(self.W2.T)
        self.z2_delta=self.z2_error*self.sigmoidPrime(self.z2)
        self.W1+=X.T.dot(self.z2_delta)
        self.W2+=self.z2.T.dot(self.o_delta)
        
        
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s*(1-s)
    
    def train(self, X,y):
        o=self.forward(X)
        self.backward(X,y,o)

In [11]:
NN = NeuralNetwork()
for i in range(1000): # trains the NN 1,000 times
    print ("\nInput: \n" + str(X))
    print ("\nActual Output: \n" + str(y)) 
    print ("\nPredicted Output: \n" + str(NN.forward(X)))
    print ("\nLoss: \n" + str(np.mean(np.square(y - NN.forward(X)))))     # mean sum squared loss)
    NN.train(X, y)


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.22226969]
 [0.2466017 ]
 [0.23942173]]

Loss: 
0.4287790457577978

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.31318578]
 [0.33110528]
 [0.31964274]]

Loss: 
0.3244201739734149

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.42324909]
 [0.4304056 ]
 [0.41367214]]

Loss: 
0.21940034813675457

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.5300403 ]
 [0.52560997]
 [0.50466747]]

Loss: 
0.13745547109641268

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Pr


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90832289]
 [0.87981154]
 [0.88108124]]

Loss: 
0.00020279876322346923

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90832055]
 [0.87980485]
 [0.88108848]]

Loss: 
0.00020268560532468854

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90831821]
 [0.87979816]
 [0.88109572]]

Loss: 
0.00020257260876635927

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90831587]
 [0.87979148]
 [0.88110294]]

Loss: 
0.00020245977322930244

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86